name: Release on manifest version change

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get previous version
        id: prev
        run: |
          PREV_VERSION=$(git show HEAD~1:manifest.json | jq -r .version || echo "")
          echo "PREV_VERSION=$PREV_VERSION" >> $GITHUB_ENV

      - name: Get current version
        id: curr
        run: |
          CURR_VERSION=$(jq -r .version manifest.json)
          echo "CURR_VERSION=$CURR_VERSION" >> $GITHUB_ENV

      - name: Create Release if version changed
        if: env.PREV_VERSION != env.CURR_VERSION
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.CURR_VERSION }}
          name: Release ${{ env.CURR_VERSION }}
          body: "Release gerada automaticamente para a versão ${{ env.CURR_VERSION }}"
          files: |
            manifest.json
            background.js
            popup.html
            popup.js
            package.json
          token: ${{ secrets.GH_RELEASE_TOKEN }}